# This is a basic workflow to deploy a release artifact

name: GITHUB_ACTIONS_DEPLOY_HELLOWORLD

on:
 project_card:
    types: [moved]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    runs-on: ubuntu-latest
      
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2-beta
      with:
        node-version: '12'

    - name: Install dependencies
      run: echo ${{secrets.GITHUB_API}}

    - name: Install dependencies
      run: npm install

    - name: Show run
      run: EVENT=${{ github.event_path }} SECRET=${{secrets.GITHUB_API}} npm run deploy

    