# This is a basic workflow to deploy a release artifact

name: GITHUB_ACTIONS_DEPLOY_HELLOWORLD

on:
 project_card:
    types: [moved]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    runs-on: ubuntu-latest
      
    steps:
    - name: Show run
      run: ls
      run: pwd
      run: EVENT=${{ github.event_path }} npm run deploy